// src/components/navigations/Frame.tsx
import React, { ReactNode } from 'react'
import { classNames } from '@/helpers'

interface IFrameProps {
  children: ReactNode
  sidebar?: ReactNode
  header?: ReactNode
  className?: string
}

export function Frame({ children, sidebar, header, className }: IFrameProps) {
  return (
    <div className={classNames('w-full min-h-screen bg-gray-100', className)}>
      {header}
      <div className="flex w-full">
        {sidebar}
        {children}
      </div>
    </div>
  )
}

// packages/vue/src/components/navigations/Frame.vue
<script setup lang="ts">
/* No need to define props for header/sidebar since we’ll use slots */
</script>

<template>
  <div class="w-full min-h-screen bg-gray-100 flex flex-col">
    <!-- Header slot -->
    <slot name="header" />

    <div class="flex w-full">
      <!-- Sidebar slot -->
      <slot name="sidebar" />

      <!-- Main content slot -->
      <slot />
    </div>
  </div>
</template>
