// src/components/forms/InlineError.tsx
import { classNames } from '@/helpers'
import React from 'react'

export function InlineError({ message, className = '' }: { message?: string; className?: string }) {
  if (!message) {
    return null
  }
  return (
    <div className={classNames('text-red-600 flex gap-2 text-xs items-center mt-1', className)}>
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
        strokeWidth={1.5}
        stroke="currentColor"
        className="w-4 h-4"
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          d="M12 9v3.75m9-.75a9 9 0 11-18 0 9 9 0 0118 0zm-9 3.75h.008v.008H12v-.008z"
        />
      </svg>

      <p>{message}</p>
    </div>
  )
}

// packages/vue/src/components/forms-selections/InlineError.vue
<template>
  <div :class="errorClasses">
    <div class="flex">
      <div class="flex-shrink-0">
        <svg class="h-5 w-5 text-red-400" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd" />
        </svg>
      </div>
      
      <div class="ml-3">
        <p :class="messageClasses">
          {{ message }}
        </p>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { classNames } from '../../helpers'

interface Props {
  message: string
  className?: string
}

const props = withDefaults(defineProps<Props>(), {
  className: ''
})

const errorClasses = computed(() => 
  classNames(
    'rounded-md bg-red-50 p-4',
    props.className
  )
)

const messageClasses = computed(() => 
  'text-sm font-medium text-red-800'
)
</script>
