// packages/vue/src/components/feedbacks/Spinner.vue
<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    :class="spinnerClasses"
    viewBox="0 0 100 100"
  >
    <circle
      cx="50"
      cy="50"
      fill="none"
      stroke="currentColor"
      stroke-width="10"
      r="35"
      stroke-dasharray="164.93361431346415 56.97787143782138"
      transform="matrix(1,0,0,1,0,0)"
    />
  </svg>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { classNames } from '../../helpers'

interface Props {
  className?: string
  size?: 'medium' | 'large' | 'small' | 'none'
}

const props = withDefaults(defineProps<Props>(), {
  className: '',
  size: 'medium'
})

const SIZE = {
  large: 'h-8 w-8',
  medium: 'h-6 w-6',
  small: 'h-5 w-5',
  none: '',
}

const spinnerClasses = computed(() => 
  classNames(props.className, SIZE[props.size], 'animate-spin')
)
</script>

// packages/react/src/components/feedbacks/Spinner.tsx
import { classNames } from '@/helpers'
import React from 'react'
interface ISpinnerProps {
  className?: string
  size?: 'medium' | 'large' | 'small' | 'none'
}
const SIZE = {
  large: 'h-8 w-8',
  medium: 'h-6 w-6',
  small: 'h-5 w-5',
  none: '',
}
export function Spinner({ className = '', size = 'medium' }: ISpinnerProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      className={classNames(className, SIZE[size], 'animate-spin')}
      viewBox="0 0 100 100"
    >
      <circle
        cx="50"
        cy="50"
        fill="none"
        stroke="currentColor"
        strokeWidth="10"
        r="35"
        strokeDasharray="164.93361431346415 56.97787143782138"
        transform="matrix(1,0,0,1,0,0)"
      />
    </svg>
  )
}
