// packages/vue/src/components/feedbacks/ExceptionList.vue
<template>
  <ul :class="listClasses">
    <li
      v-for="(item, index) in items"
      :key="index"
      :class="itemClasses"
    >
      <div class="flex">
        <div v-if="item.icon" class="flex-shrink-0">
          <component :is="item.icon" class="h-5 w-5 text-gray-400" />
        </div>
        
        <div class="ml-3">
          <p v-if="item.title" :class="titleClasses">
            {{ item.title }}
          </p>
          <p v-if="item.description" :class="descriptionClasses">
            {{ item.description }}
          </p>
        </div>
      </div>
    </li>
  </ul>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { classNames } from '../../helpers'
import type { IconType } from '../../types'

interface ExceptionItem {
  icon?: IconType
  title?: string
  description?: string
}

interface Props {
  items: ExceptionItem[]
  gap?: number
  className?: string
}

const props = withDefaults(defineProps<Props>(), {
  gap: 2,
  className: ''
})

const listClasses = computed(() => 
  classNames(
    'list-none p-0 m-0',
    props.className
  )
)

const itemClasses = computed(() => 
  classNames(
    'flex items-start',
    `mb-${props.gap}`
  )
)

const titleClasses = computed(() => 
  'text-sm font-medium text-gray-900'
)

const descriptionClasses = computed(() => 
  'text-sm text-gray-600'
)
</script>

// src/components/feedbacks/ExceptionList.tsx
import React from 'react'
import { classNames } from '@/helpers'
import { GAP } from '@/constants'
import { IconType } from '@/types'

export interface IExceptionListItem {
  icon: IconType
  description: string
}
interface IExceptionListProps {
  className?: string
  items?: IExceptionListItem[]
  gap?: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10
  message?: string
}

export function ExceptionList({ items, className = '', gap = 3 }: IExceptionListProps) {
  if (!items?.length) {
    return null
  }
  return (
    <ul className={classNames('flex flex-col w-full text-xs', className, GAP[gap])}>
      {items.map((item, idx) => (
        <li key={idx} className="flex gap-2 items-center">
          {item.icon && <item.icon className="w-4 h-4 fill-current" />}
          <p>{item.description}</p>
        </li>
      ))}
    </ul>
  )
}
