// src/components/layout-structure/EmptyState.tsx
import { classNames } from '@/helpers'
import { ButtonType, IAction, IconType } from '@/types'
import React, { ReactNode, useMemo } from 'react'

interface IActionVariant extends IAction {
  variant?: ButtonType
}
interface IEmptyStateProps {
  className?: string
  heading?: string
  actions?: IActionVariant[]
  thumb?: IconType
  children?: ReactNode
}
export function EmptyState({ children, className, heading, ...props }: IEmptyStateProps) {
  const thumb = useMemo(
    () =>
      typeof props.thumb === 'string' ? (
        <img src={props.thumb} alt={heading || ''} className="w-20 object-contain" />
      ) : (
        <div className="w-8 h-8 block">{props.thumb}</div>
      ),
    [props.thumb],
  )
  return (
    <div
      className={classNames(
        'flex flex-col items-center justify-center text-center my-5',
        className,
      )}
    >
      <div className="flex">{thumb}</div>
      <h3 className="text-lg text-center mt-4 mb-2 font-medium text-gray-800">{heading}</h3>
      <div className="text-sm text-gray-500 max-w-xl ">{children}</div>
    </div>
  )
}

// packages/vue/src/components/layout-structure/EmptyState.vue
<template>
  <div :class="emptyStateClasses">
    <div class="text-center">
      <div v-if="thumb" class="mx-auto h-12 w-12 text-gray-400">
        <img
          v-if="typeof thumb === 'string'"
          :src="thumb"
          :alt="heading"
          class="h-12 w-12"
        />
        <component
          v-else
          :is="thumb"
          class="h-12 w-12"
        />
      </div>
      
      <h3 v-if="heading" :class="headingClasses">
        {{ heading }}
      </h3>
      
      <div class="mt-2">
        <slot />
      </div>
      
      <div v-if="actions && actions.length > 0" class="mt-6">
        <div class="flex justify-center space-x-3">
          <Button
            v-for="action in actions"
            :key="action.label"
            :variant="action.variant || 'primary'"
            @click="action.onAction"
          >
            {{ action.label }}
          </Button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { classNames } from '../../helpers'
import { Button } from '../actions'
import type { IconType, IAction } from '../../types'

interface Props {
  heading?: string
  thumb?: string | IconType
  actions?: IAction[]
  className?: string
}

const props = withDefaults(defineProps<Props>(), {
  className: ''
})

const emptyStateClasses = computed(() => 
  classNames(
    'text-center py-12',
    props.className
  )
)

const headingClasses = computed(() => 
  'text-lg font-medium text-gray-900'
)
</script>
