// packages/vue/src/components/layout-structure/MediaCard.vue
<template>
  <Box
    :class="[
      props.className,
      'bg-white flex flex-col lg:flex-row overflow-hidden',
    ]"
    rounded="md"
    shadow="md"
    as="section"
  >
    <div class="relative aspect-[16/9]">
      <img
        :src="props.url"
        alt=""
        class="aspect-video object-cover flex h-full w-full"
      />
    </div>
    <div class="flex-1 px-5 py-2.5">
      <div class="flex mb-2">
        <h3 class="text-lg font-medium flex-1">{{ props.title }}</h3>
        <div class="flex gap-1 items-center -mt-1.5">
          <Button
            v-if="props.promotedAction"
            link
            :disabled="props.promotedAction.disabled"
            :loading="props.promotedAction.loading"
            :icon="props.promotedAction.icon"
            @click="props.promotedAction.onAction"
            variant="info"
            size="small"
            class="-mt-0.5"
          >
            {{ props.promotedAction.label }}
          </Button>

          <Popover v-if="props.popoverActions?.length">
            <template #activator>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                stroke-width="1.5"
                stroke="currentColor"
                class="w-6 h-6 hover:text-gray-950 text-gray-600 cursor-pointer"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  d="M6.75 12a.75.75 0 11-1.5 0 .75.75 0 011.5 0zM12.75 12a.75.75 0 11-1.5 0 .75.75 0 011.5 0zM18.75 12a.75.75 0 11-1.5 0 .75.75 0 011.5 0z"
                />
              </svg>
            </template>
            <div class="p-3 flex flex-col gap-1">
              <Button
                v-for="(action, idx) in props.popoverActions"
                :key="idx"
                :disabled="action.disabled"
                @click="action.onAction"
                :url="action.url"
                :target="action.target"
                :rel="action.rel"
                :variant="action.variant || 'ghost'"
                fullwidth
                alignment="start"
              >
                {{ action.label }}
              </Button>
            </div>
          </Popover>
        </div>
      </div>
      <div class="text-sm text-gray-600">
        <slot />
      </div>
      <div v-if="props.primaryAction?.length" class="flex gap-2 mt-4">
        <Button
          v-for="(action, idx) in props.primaryAction"
          :key="idx"
          :disabled="action.disabled"
          @click="action.onAction"
          :url="action.url"
          :target="action.target"
          :rel="action.rel"
          :variant="action.variant || 'default'"
        >
          {{ action.label }}
        </Button>
      </div>
    </div>
  </Box>
</template>

<script setup lang="ts">
import {Box,Button,Popover } from '../../components'
import { BUTTON_VARIANT } from '../../constants/common'

interface IAction {
  label: string
  onAction?: () => void
  target?: '_blank' | '_self' | '_parent'
  url?: string
  disabled?: boolean
  loading?: boolean
  icon?: any
  variant?: keyof typeof BUTTON_VARIANT | 'none'
  rel?: 'noreferrer'
}
interface IMediaCardProps {
  children?: any
  className?: string
  title?: string
  url?: string
  promotedAction?: IAction
  primaryAction?: IAction[]
  secondaryActions?: IAction[]
  popoverActions?: IAction[]
}

const props = defineProps<IMediaCardProps>()
</script>

// src/components/layout-structure/MediaCard.tsx
import React from 'react'
import { Box } from './Box'
import { classNames } from '@/helpers'
import { IAction } from '@/types'
import { Button } from '../actions'
import { Popover } from '../forms'
interface IMediaCardProps {
  children?: React.ReactNode
  className?: string
  title?: string
  url?: string
  promotedAction?: IAction
  primaryAction?: IAction[]
  secondaryActions?: IAction[]
  popoverActions?: IAction[]
}
export function MediaCard({
  children,
  className,
  title,
  url,
  promotedAction,
  popoverActions,
  primaryAction,
}: IMediaCardProps) {
  const activator = (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      strokeWidth={1.5}
      stroke="currentColor"
      className="w-6 h-6 hover:text-gray-950 text-gray-600 cursor-pointer"
    >
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M6.75 12a.75.75 0 11-1.5 0 .75.75 0 011.5 0zM12.75 12a.75.75 0 11-1.5 0 .75.75 0 011.5 0zM18.75 12a.75.75 0 11-1.5 0 .75.75 0 011.5 0z"
      />
    </svg>
  )
  return (
    <Box
      className={classNames(className, 'bg-white flex flex-col lg:flex-row overflow-hidden')}
      rounded="md"
      shadow="md"
      as="section"
    >
      <div className="relative aspect-[16/9]">
        <img src={url} alt="" className="aspect-video object-cover flex h-full w-full" />
      </div>
      <div className="flex-1 px-5 py-2.5">
        <div className="flex mb-2">
          <h3 className="text-lg font-medium flex-1">{title}</h3>
          <div className="flex gap-1 items-center -mt-1.5">
            {promotedAction && (
              <Button
                link
                disabled={promotedAction.disabled}
                loading={promotedAction.loading}
                icon={promotedAction.icon}
                onClick={promotedAction.onAction}
                variant="info"
                size="small"
                className="-mt-0.5"
              >
                {promotedAction.label}
              </Button>
            )}
            {!!popoverActions?.length && (
              <Popover activator={activator}>
                <div className="p-3 flex flex-col gap-1">
                  {popoverActions.map(
                    ({ label, onAction, target, url, disabled, variant = 'ghost', rel }, idx) => (
                      <Button
                        key={idx}
                        disabled={disabled}
                        onClick={onAction}
                        url={url}
                        target={target}
                        rel={rel}
                        variant={variant}
                        fullwidth
                        alignment="start"
                      >
                        {label}
                      </Button>
                    ),
                  )}
                </div>
              </Popover>
            )}
          </div>
        </div>
        <div className="text-sm text-gray-600">{children}</div>
        {!!primaryAction?.length && (
          <div className="flex gap-2 mt-4">
            {primaryAction.map(
              ({ label, onAction, target, url, disabled, variant = 'default', rel }, idx) => (
                <Button
                  key={idx}
                  disabled={disabled}
                  onClick={onAction}
                  url={url}
                  target={target}
                  rel={rel}
                  variant={variant}
                >
                  {label}
                </Button>
              ),
            )}
          </div>
        )}
      </div>
    </Box>
  )
}
